// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using webApi.Data;

#nullable disable

namespace webApi.Migrations
{
    [DbContext(typeof(SwiftFoundContext))]
    partial class SwiftFoundContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("webApi.Models.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Boolean")
                        .HasColumnType("bit");

                    b.Property<string>("Czas")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Data")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Dataczas")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("DuzoMissingowInt")
                        .HasColumnType("int");

                    b.Property<float>("Float")
                        .HasColumnType("real");

                    b.Property<int>("Int")
                        .HasColumnType("int");

                    b.Property<string>("Mieszane")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Mieszane2")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Pusta")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Items");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Boolean = true,
                            Czas = "10:10",
                            Data = "11-02-1980",
                            Dataczas = "11-02-1980 13:13:31",
                            Float = 2.2f,
                            Int = 1,
                            Mieszane = "ala",
                            Mieszane2 = "1"
                        },
                        new
                        {
                            Id = 2,
                            Boolean = false,
                            Czas = "10:10",
                            Float = 2.2f,
                            Int = 1,
                            Mieszane2 = "1.1"
                        },
                        new
                        {
                            Id = 3,
                            Boolean = false,
                            Czas = "10:10",
                            Data = "11-02-1980",
                            Dataczas = "11-02-1980 13:13:31",
                            Float = 0f,
                            Int = 0,
                            Mieszane = "kot",
                            Mieszane2 = "x"
                        },
                        new
                        {
                            Id = 4,
                            Boolean = false,
                            Data = "11-02-1980",
                            Dataczas = "11-02-1980 13:13:31",
                            Float = 2.2f,
                            Int = 0,
                            Mieszane = "1",
                            Mieszane2 = "10:10"
                        },
                        new
                        {
                            Id = 5,
                            Boolean = true,
                            Dataczas = "11-02-1980 13:13:31",
                            Float = 2.2f,
                            Int = 1,
                            Mieszane = "2",
                            Mieszane2 = "12-01-2020 10:10"
                        },
                        new
                        {
                            Id = 6,
                            Boolean = false,
                            Czas = "10:10",
                            Data = "11-02-1980",
                            Dataczas = "11-02-1980 13:13:31",
                            Float = 2.2f,
                            Int = 1,
                            Mieszane = "3",
                            Mieszane2 = "12-12-2020"
                        },
                        new
                        {
                            Id = 7,
                            Boolean = false,
                            Czas = "10:10",
                            Data = "11-02-1980",
                            Float = 0f,
                            Int = 1,
                            Mieszane = "4"
                        },
                        new
                        {
                            Id = 8,
                            Boolean = true,
                            Czas = "10:10",
                            Data = "11-02-1980",
                            Dataczas = "11-02-1980 13:13:31",
                            DuzoMissingowInt = 1,
                            Float = 2.2f,
                            Int = 1,
                            Mieszane = "5",
                            Mieszane2 = "True"
                        });
                });

            modelBuilder.Entity("webApi.Models.ItemLocation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<string>("Latitude")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Longitude")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.ToTable("ItemLocations");
                });

            modelBuilder.Entity("webApi.Models.ItemLocation", b =>
                {
                    b.HasOne("webApi.Models.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");
                });
#pragma warning restore 612, 618
        }
    }
}
